# Try/catch/finally

## Try/catch
O `try-catch` em Scala além de gerenciar excessões ele é um expressão aonde em seu `catch` pode ser utilizado igual a uma expressão `match`, aonde, ao criar`cases` você possui diferentes possibilidades de excessões e que serão retornadas caso ocorra.

```Scala
import java.io.FileNotFoundException
import java.io.IOException

var texto = ""

try{
  texto = openAndReadFile(fileName)
}catch{
  case e: FileNotFoundException => println("Nao foi possivel encontrar este arquivo")
  case e: IOException => println("Existe um IOException tentando ler este arquivo")
}
```

O `FileNotFoundException` e `IOException` são classes importadas do `Java`, como `Scala` tem a possibilidade de utilizar importações vindas do `Java` em alguns casos são úteis, como este, para validar excessões de erro e caso a exceção entre em um dos `cases` a requisição irá terminar.

## try/catch/finally
Além da sintaxe acima, Scala possui mais uma opção, o `finally`aonde geralmente é usado para fechar recursos
(ex: conexões com banco de dados)

```Scala
try{
  // Código em Scala que é criado para realizar tentativa de execução
  // antes de acessar as sintaxes abaixo
}catch{
  case exc1: primeiraExcessao => gerenciarPrimeiraExcessao(exc1)
  case exc2: segundaExcessao => gerenciarSegundaExcessao(exc2)
  case _: Throwable => println("Um outro tipo de exception usando Throwable excessao")
}finally{
    // Codigo Scala para fechar conexões com banco de dados
    // ou gerenciar arquivos
}
```
